# Generated by Django 3.2.9 on 2021-12-27 13:04

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CED_Tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intitule', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ced_departements',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('etablissement', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ced_enseignants',
            },
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intitule', models.CharField(max_length=255)),
                ('acronyme', models.CharField(max_length=255)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='laboratoires', to='Administration.departement')),
            ],
            options={
                'db_table': 'ced_laboratoires',
            },
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intitule', models.CharField(max_length=255)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sujets', to='CED_Tools.annee')),
                ('co_directeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='co_sujets', to='Administration.enseignant')),
                ('directeur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sujets', to='Administration.enseignant')),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sujets', to='Administration.laboratoire')),
            ],
            options={
                'db_table': 'ced_sujets',
            },
        ),
        migrations.CreateModel(
            name='LaboratoireDirecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courant', models.BooleanField(default=True)),
                ('directeur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='laboratoire_courant', to='Administration.enseignant')),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='directeur_courant', to='Administration.laboratoire')),
            ],
            options={
                'db_table': 'ced_laboratoire_directeur',
            },
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='directeurs',
            field=models.ManyToManyField(through='Administration.LaboratoireDirecteur', to='Administration.Enseignant'),
        ),
    ]
