# Generated by Django 3.2.9 on 2022-03-23 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CED_Tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('intitule', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ced_departements',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('cin', models.CharField(blank=True, max_length=50, null=True)),
                ('som', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
            options={
                'db_table': 'ced_enseignants',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('acronyme', models.CharField(max_length=63)),
                ('intitule', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='etablissements', to='CED_Tools.pays')),
            ],
            options={
                'db_table': 'ced_etablissements',
            },
        ),
        migrations.CreateModel(
            name='FormationDoctorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('intitule', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('acronyme', models.CharField(max_length=255)),
                ('co_ordonateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='formations_doctorales', to='Administration.enseignant')),
            ],
            options={
                'db_table': 'ced_formations_doctorales',
            },
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('intitule', models.CharField(max_length=255)),
                ('acronyme', models.CharField(max_length=255)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='laboratoires', to='Administration.departement')),
                ('formation_doctorale', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='laboratoires', to='Administration.formationdoctorale')),
            ],
            options={
                'db_table': 'ced_laboratoires',
            },
        ),
        migrations.CreateModel(
            name='TypeFormationComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('intitule', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ced_types_formations_complementaires',
            },
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('intitule', models.TextField(max_length=255)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sujets', to='CED_Tools.annee')),
                ('co_directeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='co_sujets', to='Administration.enseignant')),
                ('directeur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sujets', to='Administration.enseignant')),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sujets', to='Administration.laboratoire')),
            ],
            options={
                'db_table': 'ced_sujets',
            },
        ),
        migrations.CreateModel(
            name='LocalisationSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('intitule', models.CharField(max_length=255)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Administration.etablissement')),
            ],
            options={
                'db_table': 'ced_localisations_soutenance',
            },
        ),
        migrations.CreateModel(
            name='LaboratoireDirecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('courant', models.BooleanField(default=True)),
                ('directeur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='laboratoires', to='Administration.enseignant')),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='directeurs', to='Administration.laboratoire')),
            ],
            options={
                'db_table': 'ced_laboratoire_directeur',
            },
        ),
        migrations.CreateModel(
            name='FormationComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('intitule', models.CharField(max_length=255)),
                ('volume_horaire', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('formation_doctorale', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='formations_complementaires', to='Administration.formationdoctorale')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='formations_complementaires', to='Administration.typeformationcomplementaire')),
            ],
            options={
                'db_table': 'ced_formations_complementaires',
            },
        ),
        migrations.AddField(
            model_name='enseignant',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enseignants', to='Administration.etablissement'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='laboratoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enseignants', to='Administration.laboratoire'),
        ),
    ]
