# Generated by Django 3.2.9 on 2022-01-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CED_Tools', '0001_initial'),
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sujets', to='CED_Tools.annee'),
        ),
        migrations.AddField(
            model_name='sujet',
            name='co_directeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='co_sujets', to='Administration.enseignant'),
        ),
        migrations.AddField(
            model_name='sujet',
            name='directeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sujets', to='Administration.enseignant'),
        ),
        migrations.AddField(
            model_name='sujet',
            name='laboratoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sujets', to='Administration.laboratoire'),
        ),
        migrations.AddField(
            model_name='laboratoiredirecteur',
            name='directeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='laboratoires', to='Administration.enseignant'),
        ),
        migrations.AddField(
            model_name='laboratoiredirecteur',
            name='laboratoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='directeurs', to='Administration.laboratoire'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='laboratoires', to='Administration.departement'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='formation_doctorale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='laboratoires', to='Administration.formationdoctorale'),
        ),
        migrations.AddField(
            model_name='formationdoctorale',
            name='co_ordonateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='formations_doctorales', to='Administration.enseignant'),
        ),
        migrations.AddField(
            model_name='formationcomplementaire',
            name='formation_doctorale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='formations_complementaires', to='Administration.formationdoctorale'),
        ),
        migrations.AddField(
            model_name='formationcomplementaire',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='formations_complementaires', to='Administration.typeformationcomplementaire'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='etablissements', to='CED_Tools.pays'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enseignants', to='Administration.etablissement'),
        ),
    ]
