# Generated by Django 3.2.9 on 2022-02-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='intitule',
            field=models.TextField(max_length=255),
        ),
    ]
