# Generated by Django 3.2.9 on 2022-01-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalisationSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intitule', models.CharField(max_length=255)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Administration.etablissement')),
            ],
            options={
                'db_table': 'ced_localisations_soutenance',
            },
        ),
    ]
