# Generated by Django 3.2.9 on 2022-01-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_localisationsoutenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
