# Generated by Django 3.2.9 on 2022-03-23 14:16

import CED_Tools.models
import CED_Tools.tools.Functions
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CED_Tools', '0001_initial'),
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('intitule', models.CharField(max_length=255)),
                ('acronyme', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=255)),
                ('duree_annees', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Types de Cursus',
                'db_table': 'ced_cursus_types',
            },
        ),
        migrations.CreateModel(
            name='Doctorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to=CED_Tools.tools.Functions.photo_upload_to)),
                ('nom', models.CharField(max_length=63)),
                ('prenom', models.CharField(max_length=63)),
                ('sexe', models.CharField(choices=[('m', 'Masculine'), ('f', 'Feminine')], max_length=1)),
                ('cne', models.CharField(max_length=15, verbose_name='CNE')),
                ('cin', models.CharField(max_length=15, unique=True, verbose_name='CIN')),
                ('date_naissance', models.CharField(blank=True, max_length=10, null=True, validators=[CED_Tools.tools.Functions.birhdayValidator], verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de naissance')),
                ('nom_ar', models.CharField(blank=True, max_length=127, null=True)),
                ('prenom_ar', models.CharField(blank=True, max_length=127, null=True)),
                ('lieu_naissance_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=127, null=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email_ac', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Académique')),
                ('email_pr', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Personnelle')),
                ('cv', models.FileField(blank=True, max_length=255, null=True, upload_to=CED_Tools.tools.Functions.cv_upload_to, verbose_name='Curriculum Vitae')),
                ('handicap', models.CharField(blank=True, choices=[('auditif', 'Auditif'), ('visuel', 'Visuel'), ('autre', 'Autre')], max_length=31, null=True)),
                ('situation_f', models.CharField(blank=True, choices=[('m', 'Marié'), ('c', 'Célébataire')], max_length=1, null=True)),
                ('fonctionnaire', models.BooleanField(blank=True, default=False, null=True)),
                ('employeur', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('search_indexer', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.ForeignKey(blank=True, default=CED_Tools.models.Pays.default_value_id, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctorants', to='CED_Tools.pays')),
            ],
            options={
                'db_table': 'ced_doctorants',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sujet_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('annee', models.ForeignKey(default=CED_Tools.tools.Functions.current_year, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscriptions', to='CED_Tools.annee')),
                ('doctorant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscriptions', to='Etudiant.doctorant')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscriptions', to='Administration.sujet')),
            ],
            options={
                'db_table': 'ced_inscriptions',
            },
        ),
        migrations.CreateModel(
            name='RetraitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('intitule', models.CharField(max_length=255)),
                ('max_delais', models.IntegerField(default=3, verbose_name='Délais Maximum')),
            ],
            options={
                'verbose_name_plural': 'Types de documents à retirer',
                'db_table': 'ced_retraits_types',
            },
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('speciality', models.CharField(blank=True, max_length=255, null=True, verbose_name='spécialité')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('doctorant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='soutenances', to='Etudiant.doctorant')),
            ],
            options={
                'db_table': 'ced_soutenances',
            },
        ),
        migrations.CreateModel(
            name='SoutenanceMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('rapporteur', models.BooleanField(default=False)),
                ('emailed', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Administration.enseignant')),
                ('soutenance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Etudiant.soutenance')),
            ],
            options={
                'db_table': 'ced_soutenence_members',
            },
        ),
        migrations.CreateModel(
            name='SoutenanceEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('address', models.EmailField(max_length=254)),
                ('sended', models.BooleanField(default=False)),
                ('error_message', models.CharField(max_length=255, null=True)),
                ('soutenance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emails', to='Etudiant.soutenance')),
            ],
            options={
                'db_table': 'ced_soutenance_emails',
            },
        ),
        migrations.AddField(
            model_name='soutenance',
            name='enseignants',
            field=models.ManyToManyField(through='Etudiant.SoutenanceMembers', to='Administration.Enseignant'),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='soutenances', to='Administration.localisationsoutenance'),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='soutenances', to='Administration.enseignant'),
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date création')),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('definitif', models.BooleanField(default=False)),
                ('doctorant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='retraits', to='Etudiant.doctorant')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='retraits', to='Etudiant.retraittype')),
            ],
            options={
                'verbose_name_plural': 'Retraits',
                'db_table': 'ced_retraits',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('intitule', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='publications', to='Etudiant.inscription')),
            ],
            options={
                'db_table': 'ced_publications',
            },
        ),
        migrations.CreateModel(
            name='Formation_C_Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('formation_complementaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscriptions', to='Administration.formationcomplementaire')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fomations_complementaires', to='Etudiant.inscription')),
            ],
            options={
                'db_table': 'ced_fc_inscription',
            },
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('intitule', models.CharField(max_length=255)),
                ('date_obtention', models.DateField(blank=True, null=True, verbose_name="Date d'obtention")),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)])),
                ('duree', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée (ans)')),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('etablissement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Etablissement')),
                ('photo_diplome', models.FileField(blank=True, max_length=255, null=True, upload_to=CED_Tools.tools.Functions.cursus_document_upload_to, verbose_name='Diplôme')),
                ('photo_releve', models.FileField(blank=True, max_length=255, null=True, upload_to=CED_Tools.tools.Functions.cursus_document_upload_to, verbose_name='Relevé des notes')),
                ('annee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cursus', to='CED_Tools.annee')),
                ('doctorant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cursus', to='Etudiant.doctorant')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cursus', to='Etudiant.cursustype')),
            ],
            options={
                'verbose_name_plural': 'Cursus',
                'db_table': 'ced_cursus',
            },
        ),
    ]
