# Generated by Django 3.2.9 on 2022-02-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
