# Generated by Django 3.2.9 on 2022-01-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_localisationsoutenance'),
        ('Etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Etudiant.inscription')),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Administration.localisationsoutenance')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Administration.enseignant')),
            ],
            options={
                'db_table': 'ced_soutenances',
            },
        ),
        migrations.CreateModel(
            name='SoutenanceMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rapporteur', models.BooleanField(default=False)),
                ('menmber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Administration.enseignant')),
                ('soutenance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Etudiant.soutenance')),
            ],
            options={
                'db_table': 'ced_soutenence_members',
            },
        ),
    ]
