# Generated by Django 3.2.9 on 2022-01-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='doctorant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='soutenances', to='Etudiant.doctorant'),
        ),
    ]
