# Generated by Django 3.2.9 on 2022-02-16 13:58

import CED_Tools.models
import CED_Tools.tools.Functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CED_Tools', '0001_initial'),
        ('Etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorant',
            name='situation_f',
            field=models.CharField(blank=True, choices=[('m', 'Marié'), ('c', 'Célébataire')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='date_naissance',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[CED_Tools.tools.Functions.birhdayValidator], verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='fonctionnaire',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='pays',
            field=models.ForeignKey(blank=True, default=CED_Tools.models.Pays.default_value_id, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctorants', to='CED_Tools.pays'),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='sexe',
            field=models.CharField(choices=[('m', 'Masculine'), ('f', 'Feminine')], max_length=1),
        ),
    ]
