# Generated by Django 3.2.9 on 2022-02-23 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CED_Tools', '0001_initial'),
        ('Etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursus',
            name='annee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cursus', to='CED_Tools.annee'),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='duree',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée (ans)'),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='etablissement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Etablissement'),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='ville',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
