# Generated by Django 3.2.9 on 2022-01-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0002_alter_soutenance_doctorant'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='speciality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
