# Generated by Django 3.2.9 on 2022-02-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_initial'),
        ('Etudiant', '0002_alter_soutenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='soutenances', to='Administration.localisationsoutenance'),
        ),
    ]
