# Generated by Django 3.2.9 on 2022-01-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0002_soutenance_soutenancemembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soutenancemembers',
            old_name='menmber',
            new_name='member',
        ),
    ]
