# Generated by Django 3.2.9 on 2022-01-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0003_soutenance_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='speciality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='spécialité'),
        ),
    ]
