# Generated by Django 3.2.9 on 2022-01-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0004_enseignant_grade'),
        ('Etudiant', '0003_rename_menmber_soutenancemembers_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='soutenances', to='Etudiant.inscription'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='localisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='soutenances', to='Administration.localisationsoutenance'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='soutenances', to='Administration.enseignant'),
        ),
    ]
