# Generated by Django 3.2.9 on 2022-02-16 14:54

import CED_Tools.tools.Functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0003_auto_20220216_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursus',
            name='photo_diplome',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=CED_Tools.tools.Functions.cursus_document_upload_to, verbose_name='Diplôme'),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='photo_releve',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=CED_Tools.tools.Functions.cursus_document_upload_to, verbose_name='Relevé des notes'),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='cv',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=CED_Tools.tools.Functions.cv_upload_to, verbose_name='Curriculum Vitae'),
        ),
        migrations.AlterField(
            model_name='doctorant',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=CED_Tools.tools.Functions.photo_upload_to),
        ),
    ]
